server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 2000
      database: 0
      username: redis_user
      password: redis_user
