apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app
  namespace: redis
spec:
  containers:
    - name: spring-boot-app
      image: sample-aspect
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATA_REDIS_USERNAME
          value: default
        - name: SPRING_DATA_REDIS_HOST
          value: redis-service

