version: '3.8'

services:
  redis:
    container_name: redis-container
    image: 'public.ecr.aws/docker/library/redis:7.0.15'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis-data:

# docker compose up -d
# docker compose down
